DROP TABLE IF EXISTS "Product";
DROP TABLE IF EXISTS "Store";


CREATE TABLE "Store" (
    "Id" SERIAL PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL,
    "Address" VARCHAR(255) NOT NULL,
	"PhoneNumber" VARCHAR(10) NOT NULL,
	"IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
	"DateCreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"DateUpdated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"CreatedByUserId" INT NOT NULL,
	"UpdatedByUserId" INT NOT NULL
);

CREATE TABLE "Product" (
    "Id" SERIAL PRIMARY KEY,
	"StoreId" INT NOT NULL,
    "Name" VARCHAR(255) NOT NULL,
    "Price" DECIMAL (4,2) NOT NULL,
	"ExpirationDate" DATE NOT NULL,
	"IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
	"DateCreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"DateUpdated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"CreatedByUserId" INT NOT NULL,
	"UpdatedByUserId" INT NOT NULL,
    CONSTRAINT "FK_Product_Store_StoreId" 
		FOREIGN KEY ("StoreId") 
		REFERENCES "Store"("Id")
);

